# Generated by Django 3.2.9 on 2022-11-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_solaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blognumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solaman',
            name='blognumber',
            field=models.IntegerField(default=1),
        ),
    ]
